# Generated by Django 3.0.4 on 2020-05-23 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0012_reservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='checkin',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='checkout',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='total',
        ),
    ]
