# Generated by Django 3.0.4 on 2020-05-24 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0013_auto_20200523_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='checkin',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='checkout',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='days',
            field=models.IntegerField(),
        ),
    ]
