# Generated by Django 3.0.4 on 2020-05-15 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200515_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='aboutus',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='setting',
            name='contact',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='setting',
            name='references',
            field=models.TextField(),
        ),
    ]
